# Generated by Django 5.0.1 on 2024-01-17 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_trim', models.CharField(max_length=50)),
                ('vehicle_engine', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('part_type', models.CharField(max_length=50)),
                ('part_fitment_location', models.CharField(max_length=255)),
                ('part_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('part_interchange', models.CharField(max_length=50)),
                ('part_notes', models.CharField(max_length=255)),
                ('part_status', models.CharField(choices=[('Listed', 'Listed'), ('Sold', 'Sold'), ('Removed', 'Removed'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], default='Pending', max_length=50)),
                ('vehicle_fitment', models.CharField(max_length=500)),
                ('part_image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('part_image_10', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
