# Generated by Django 5.0.1 on 2024-01-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_trim', models.CharField(max_length=50)),
                ('vehicle_engine', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('part_type', models.CharField(max_length=50)),
                ('part_fitment_location', models.CharField(max_length=255)),
                ('part_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('part_interchange', models.CharField(max_length=50)),
                ('part_notes', models.CharField(max_length=255)),
                ('vehicle_fitment', models.CharField(max_length=500)),
                ('part_image_1', models.ImageField(upload_to='images/')),
                ('part_image_2', models.ImageField(upload_to='images/')),
                ('part_image_3', models.ImageField(upload_to='images/')),
                ('part_image_4', models.ImageField(upload_to='images/')),
                ('part_image_5', models.ImageField(upload_to='images/')),
                ('part_image_6', models.ImageField(upload_to='images/')),
                ('part_image_7', models.ImageField(upload_to='images/')),
                ('part_image_8', models.ImageField(upload_to='images/')),
                ('part_image_9', models.ImageField(upload_to='images/')),
                ('part_image_10', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
