# Generated by Django 5.0.1 on 2024-01-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='ebay_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
