# Generated by Django 5.0.1 on 2024-01-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_status',
            field=models.CharField(choices=[('Listed', 'Listed'), ('Sold', 'Sold'), ('Removed', 'Removed'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], default='Pending', max_length=50),
        ),
    ]
