# Generated by Django 3.2.23 on 2024-06-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_part_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='ebay_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='marketplace_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='mercari_listed',
            field=models.BooleanField(default=False),
        ),
    ]
