# Generated by Django 5.0.1 on 2024-01-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_part_sellers_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
