# Generated by Django 3.2.23 on 2024-06-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20240612_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
