# Generated by Django 3.2.23 on 2024-06-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_vehicle_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='stock_number',
        ),
    ]
