# Generated by Django 5.0.1 on 2024-01-20 22:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_part_sellers_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
