# Generated by Django 5.0.1 on 2024-01-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_rename_part_fitment_location_part_fitment_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_fitment_location',
            new_name='fitment_location',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_interchange',
            new_name='hollander_interchange',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_type',
            new_name='type',
        ),
    ]
