# Generated by Django 3.2.23 on 2024-06-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_part_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
