# Generated by Django 5.0.1 on 2024-01-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_rename_part_fitment_location_part_fitment_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_fitment_location',
            new_name='fitment_location',
        ),
    ]
