# Generated by Django 3.2.23 on 2024-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_part_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
