# Generated by Django 5.0.1 on 2024-01-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_rename_part_grade_part_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_interchange',
            new_name='hollander_interchange',
        ),
    ]
