# Generated by Django 3.2.23 on 2024-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Front', 'Front'), ('Back', 'Back'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('Center', 'Center')], max_length=50, null=True),
        ),
    ]
