# Generated by Django 5.0.1 on 2024-01-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_rename_part_notes_part_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_status',
            new_name='status',
        ),
    ]
