# Generated by Django 3.2.23 on 2024-06-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_part_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_9',
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.part')),
            ],
        ),
    ]
