# Generated by Django 3.2.23 on 2024-06-27 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_auto_20240627_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partimage',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='dashboards.part'),
        ),
    ]
