# Generated by Django 5.0.1 on 2024-01-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_rename_part_status_part_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_type',
            new_name='type',
        ),
    ]
