# Generated by Django 3.2.23 on 2024-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_alter_partimage_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='ebay_category_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='ebay_offer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
