# Generated by Django 3.2.23 on 2024-01-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_auto_20240124_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
