# Generated by Django 3.2.23 on 2024-01-25 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_auto_20240124_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='sku',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
