# Generated by Django 3.2.23 on 2024-01-25 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_part_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
