# Generated by Django 3.2.23 on 2024-01-26 07:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_alter_part_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('Listed', 'Listed'), ('Sold', 'Sold'), ('Removed', 'Removed'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=36)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_label', models.FileField(blank=True, null=True, upload_to='shipping_labels/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('part_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.part')),
            ],
        ),
    ]
