# Generated by Django 3.2.23 on 2024-01-26 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_auto_20240126_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='part_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.part'),
        ),
    ]
