# Generated by Django 3.2.23 on 2024-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_auto_20240128_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('make', models.CharField(blank=True, max_length=256, null=True)),
                ('model', models.CharField(max_length=256)),
                ('trim', models.CharField(blank=True, max_length=256, null=True)),
                ('primary_damage', models.CharField(blank=True, max_length=256, null=True)),
                ('secondary_damage', models.CharField(blank=True, max_length=256, null=True)),
                ('yard', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=256, null=True)),
                ('mileage', models.CharField(blank=True, max_length=256, null=True)),
                ('transmission', models.CharField(blank=True, max_length=256, null=True)),
                ('body_type', models.CharField(blank=True, max_length=256, null=True)),
                ('drivetrain', models.CharField(blank=True, max_length=256, null=True)),
                ('exterior_primary_color', models.CharField(blank=True, max_length=256, null=True)),
                ('exterior_primary_paint_code', models.CharField(blank=True, max_length=256, null=True)),
                ('exterior_secondary_color', models.CharField(blank=True, max_length=256, null=True)),
                ('exterior_secondary_paint_code', models.CharField(blank=True, max_length=256, null=True)),
                ('interior_primary_color', models.CharField(blank=True, max_length=256, null=True)),
                ('interior_primary_paint_code', models.CharField(blank=True, max_length=256, null=True)),
                ('interior_secondary_color', models.CharField(blank=True, max_length=256, null=True)),
                ('interior_secondary_paint_code', models.CharField(blank=True, max_length=256, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buyer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internet_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tow_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dismantler_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pullout_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('misc_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buyer', models.CharField(blank=True, max_length=256, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('towed_by', models.CharField(blank=True, max_length=256, null=True)),
                ('inventoried_date', models.DateField(blank=True, null=True)),
                ('dismantled_by', models.CharField(blank=True, max_length=256, null=True)),
                ('dismantled_date', models.DateField(blank=True, null=True)),
                ('crush_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
