# Generated by Django 3.2.23 on 2024-02-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0023_vehicle_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
