# Generated by Django 4.2.6 on 2024-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
