# Generated by Django 4.2.6 on 2024-02-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0025_vehicle_seller_address_vehicle_seller_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='row',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('COPART', 'COPART'), ('IAA', 'IAA'), ('Street', 'Street'), ('Charity', 'Charity'), ('Vendor', 'Vendor')], max_length=256, null=True),
        ),
    ]
