# Generated by Django 4.2.6 on 2024-02-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_location_latitude_location_longitude'),
        ('dashboards', '0027_vehicle_latitude_vehicle_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.location'),
        ),
    ]
