# Generated by Django 4.2.6 on 2024-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0028_alter_vehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='yard',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
