# Generated by Django 4.2.6 on 2024-02-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_alter_vehicle_model_alter_vehicle_yard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='marker',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
