# Generated by Django 4.2.6 on 2024-05-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_part_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vehicle_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
