# Generated by Django 4.2.6 on 2024-05-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0036_cores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cores',
            new_name='core',
        ),
    ]
