# Generated by Django 4.2.6 on 2024-05-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0039_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
