# Generated by Django 4.2.6 on 2024-05-31 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_address_line1_company_address_line2_and_more'),
        ('dashboards', '0041_core_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
    ]
