# Generated by Django 4.2.6 on 2024-06-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_address_line1_company_address_line2_and_more'),
        ('dashboards', '0042_rename_user_vehicle_creator_vehicle_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_preferences', to='company.company')),
                ('parts', models.ManyToManyField(blank=True, to='dashboards.part')),
            ],
        ),
    ]
