# Generated by Django 4.2.6 on 2024-06-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0043_partpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partpreference',
            name='parts',
        ),
        migrations.AddField(
            model_name='partpreference',
            name='parts',
            field=models.TextField(blank=True, help_text='Comma-separated list of parts'),
        ),
    ]
