MAKES_MODELS = {
    "AMC": ["Ambassador", "American", "AMX", "Classic", "Concord", "Eagle", "Gremlin", "Hornet", "Javelin", "Marlin", "Matador", "Pacer", "Rambler", "Rebel", "Spirit", "Other"],
    "Acura": ["CL", "CSX", "EL", "ILX", "Integra", "Legend", "MDX", "NSX", "RDX", "RL", "RLX", "RSX", "SLX", "TL", "TLX", "TSX", "Vigor", "ZDX"],
    "Alfa": ["147", "164 Sedan", "1750", "4C", "Alfetta", "GTV6", "Giulia", "Giulia 1600", "Giulietta", "Milano", "Mito", "Spider-1600", "Spider-1600 Duetto", "Spider-2000", "Stelvio", "Tonale"],
    "Audi": ["100", "200", "4000 2 & 4 Door Sedan", "4000 Quattro", "5000 & 5000 Quattro", "80 Series", "90 Series", "A3", "A4", "A5", "A6", "A7", "A8", "AllRoad", "AllRoad A4", "AllRoad A6", "Cabriolet", "Coupe GT", "Coupe Quattro", "E-tron", "E-tron GT", "E-tron S", "Fox", "Q3", "Q4 E-tron", "Q5", "Q7", "Q8", "R8", "RS3", "RS4", "RS5", "RS6", "RS7", "RS E-tron GT", "RS Q8", "S3", "S4", "S5", "S6", "S7", "S8", "SQ5", "SQ7", "SQ8", "Sport Coupe", "Super 90", "TT", "V8 Quattro"],
    "BMW": [
        "1M", "128i", "135i", "1602", "1800", "228i", "230i", "2002", "2500", "2800", "3.0", "318i", "320i", "323i",
        "325e", "325i", "328i", "328i GT", "330e", "330i", "330i GT", "335i", "335i GT", "340i", "340i GT", "428i",
        "430i", "435i", "440i", "524TD", "525i", "528e", "528i", "530e", "530i", "533i", "535i", "535i GT", "540i",
        "545i", "550i", "550i GT", "630CSi", "633CSi", "635CSi", "640i", "640i GT", "645Ci", "650i", "728", "732",
        "733i", "735i", "740e", "740i", "745e", "745i", "750i", "760i", "840ci", "840i", "850i", "ActiveE",
        "ActiveHybrid 3", "ActiveHybrid 5", "ActiveHybrid 7", "Alpina B6", "Alpina B7", "Alpina B8", "Alpina XB7",
        "I3", "I4", "I7", "I8", "IX", "L6", "Mini Cooper", "Mini Cooper Clubman", "Mini Cooper Countryman",
        "Mini Cooper Paceman", "M1", "M2", "M3", "M4", "M5", "M6", "M8", "M235i", "M240i", "M340i", "M440i",
        "M550i", "M760i", "M850i", "X1", "X2", "X3", "X3M", "X4", "X4M", "X5", "X5M", "X6", "X6M", "X7", "XM",
        "Z3", "Z4", "Z8", "Other"
    ],
    "Buick": [
        "Allure", "Apollo", "Cascada", "Century", "Electra (1979 Down)", "Electra (1980 Up)", "Enclave",
        "Encore", "Encore GX", "Envision", "Envista", "Lacrosse", "LeSabre (1979 Down)", "LeSabre (1980 Up)",
        "Limited", "Lucerne", "Park Ave (1979 Down)", "Park Ave (1980 Up)", "Rainier", "Reatta", "Regal",
        "Regal Somerset (1984 Down)", "Rendezvous", "Riviera", "Roadmaster (1979 Down)", "Roadmaster (1980 Up)",
        "Skyhawk", "Skylark", "Somerset (1985 Up)", "Special", "Terraza", "Verano", "Other"
    ],
    "Cadillac": [
        "Allante", "ATS", "Brougham", "CT4", "CT5", "CT6", "CTS", "Catera", "Cimarron",
        "Concours", "DeVille (1979 Down)", "DeVille (1980 Up)", "DHS", "DTS (2005 Down)",
        "DTS (2006 Up)", "ELR", "Eldorado (1966 Down)", "Eldorado (1967 Up)", "Escalade",
        "Escalade-ESV", "Escalade-EXT", "Fleetwood (1979 Down)", "Fleetwood (1980 Up)",
        "LYRIQ", "Seville (incl STS)", "SRX", "STS", "XLR", "XT4", "XT5", "XT6", "XTS", "Other"
    ],
    "Chevrolet": [
        "Astra", "Astro", "Aveo", "Beretta", "Blazer, Full Size (1994 Down)", "Blazer (2019 Up)",
        "Blazer, S10/S15", "Bolt", "Bolt EUV", "C2", "Camaro", "Caprice (1979 Down)", "Caprice (1980 Up)",
        "Captiva Sport", "Cavalier", "Celebrity", "Chevelle", "Chevette", "Chevy Pickup FWD (Non US Mkt)",
        "Chevy Small Car (Non US Mkt)", "Citation", "City Express", "Cobalt", "Corsa", "Corsica", "Corvair",
        "Corvette", "Cruze", "El Camino (1963 Down)", "El Camino (1964-1977)", "El Camino (1978 Up)", "Epica",
        "Equinox", "HHR", "Impala (1979 Down)", "Impala (1980 Up)", "Lumina Car", "Lumina Van", "Luv (See Also Isuzu Mini P-Up)",
        "Malibu", "Meriva", "Metro", "Monte Carlo", "Monza", "Nova & Chevy II (1967 Down)", "Nova (1968 Up)",
        "Optra", "Orlando", "Prizm", "S10/S15/Sonoma", "Sonic", "Spark", "Spectrum", "Sprint", "SS", "SSR",
        "Suburban-10 (1988 Down)", "Suburban-20 (1988 Down)", "Suburban-30 (1966 Down)", "Suburban-1000 (1963-1966)",
        "Suburban-1500", "Suburban-2500 (1967 Up)", "Suburban-3500", "Tahoe", "Tigra", "Tornado", "Tracker",
        "TrailBlazer", "TrailBlazer-EXT", "Traverse", "Trax", "Truck-10 Series (1987 Down)", "Truck-20 Series (1988 Down)",
        "Truck-30 Series (1988 Down)", "Truck-1500 Series (1988-1999)", "Truck-2500 Series (1988-2000)", "Truck-3500 Series (1988-2001)",
        "Truck-Avalanche 1500", "Truck-Avalanche 2500", "Truck-C3100", "Truck-C3600", "Truck-C3800", "Truck-Colorado",
        "Truck-Forward Control", "Truck-Kodiak", "Truck-Luv Mini Pup", "Truck-S10/S15/Sonoma", "Truck-Silverado 1500 (1999 Up)",
        "Truck-Silverado 2500 (1999 Up)", "Truck-Silverado 3500 (2001 Up)", "Truck-Tilt Cab", "Uplander", "Van 10", "Van 20",
        "Van 30", "Van Express 1500", "Van Express 2500", "Van Express 3500", "Vectra", "Vega", "Venture", "Volt", "Zafira", "Other"
    ],
    "Chrysler": [
        "200", "300", "300M", "Aspen", "Atos", "Attitude", "Cirrus", "Concorde", "Conquest",
        "Cordoba", "Crossfire", "E Class", "Fifth Avenue - FWD", "Fifth Avenue - RWD (1979 Up)",
        "Imperial", "LHS", "Laser", "Lebaron", "New Yorker - FWD", "New Yorker - RWD", "Newport",
        "Pacifica", "Prowler", "PT Cruiser", "Sebring", "TC", "Town and Country", "Voyager", "Other"
    ],
    "Daewoo": ["Lanos", "Leganza", "Nubira"],
    "Daihatsu": ["Charade", "Hijet", "Rocky"],
    "Dodge": [
        "400", "600", "Aries", "Aspen", "Avenger", "Caliber", "Caravan", "Challenger (Chrysler)", "Challenger (Mitsubishi)",
        "Charger", "Colt-not Vista", "Colt Vista", "Cricket", "D50/Ram 50 (See also Plymouth Arrow Truck)", "Dakota",
        "Dart", "Daytona", "Diplomat", "Durango", "Dynasty", "Intrepid", "Journey", "Lancer", "Magnum", "Mirada",
        "Monaco (1978 Down)", "Monaco (1990 Up)", "Neon", "Nitro", "Omni", "Raider", "Ramcharger", "Rampage", "Shadow",
        "Spirit", "St Regis", "Stealth", "Stratus", "Truck-100 Series (1989 Down)", "Truck-200 Series (1980 Down)",
        "Truck-300 Series (1980 Down)", "Truck-400 Series", "Truck-150 (1978-1993)", "Truck-250 Series (1981-1993)",
        "Truck-350 Series (1981-1993)", "Truck-450 Series", "Truck-1500 (1994 Up)", "Truck-2500 Series (1994 Up)",
        "Truck-3500 (1994 Up)", "Truck-4500 Series", "Truck-5500 Series", "Truck-D50/Ram 50", "Truck-Dakota",
        "Truck-Forward Control", "Truck-Rampage", "Van 100", "Van 150", "Van 200", "Van 250", "Van 300", "Van 350",
        "Van 1500", "Van 2500", "Van 3500", "Van (Sprinter 2500)", "Van (Sprinter 3500)", "Verna", "Viper", "Other"
    ],
    "Eagle": [
        "2000 GTX", "Premier", "Summit", "Talon", "Vision"
    ],
    "Fiat": [
        "1100R", "124 (1983 Down, includes Spider)", "124 Spider (2016 Up)", "128", "131/Brava",
        "500", "600", "850", "Spider (includes 2000)", "Strada", "X 1/9", "Other"
    ],
    "Ford": [
        "500", "Aerostar", "Aspire", "Bronco (Full Size)", "Bronco II", "Bronco Raptor", "Bronco Sport",
        "C-Max", "Contour", "Cortina", "Courier", "Crown Vic (1982 Down)", "Crown Vic (1983 Up)", "Ecosport",
        "Edge", "Escape", "Escort", "Excursion", "EXP", "Expedition", "Explorer", "Fairlane", "Fairmont",
        "Falcon", "Festiva", "Fiesta", "Five Hundred", "Flex", "Focus", "Focus RS", "Freestar", "Freestyle",
        "Fusion", "Galaxie", "Granada", "GT", "Ikon", "KA", "LTD (1978 Down)", "LTD (1979 Up)", "LTD II",
        "Maverick", "Maverick Pickup", "Mondeo", "Mustang", "Mustang Mach E", "Pinto", "Probe", "Ranchero (1967-1970)",
        "Ranchero (1971-1976)", "Ranchero (1977 up)", "Ranchero (1957-1959)", "Ranchero (1960-1966)", "Ranger",
        "Taurus", "Taurus X", "Tempo", "ThinkCity-Electric", "Thunderbird", "Torino", "Transit 150", "Transit 250",
        "Transit 350", "Transit Connect", "Truck-Courier", "Truck-F100", "Truck-F150", "Truck F150 Lightning (Electric)",
        "Truck-F150 Lightning (SVT Gas)", "Truck-F150 Raptor", "Truck-F250 not Super Duty (1999 Down)",
        "Truck-F250 Super Duty (1999 Up)", "Truck-F350 not Super Duty (1997 Down)", "Truck-F350 Super Duty (1999 Up)",
        "Truck-F450 not Super Duty (1997 Down)", "Truck-F450 Super Duty (1999 Up)", "Truck-F550 Super Duty (1999 Up)",
        "Truck-Forward Control", "Truck-Ranger", "Van E100", "Van E150", "Van E200", "Van E250", "Van E300",
        "Van E350", "Van E450 Super Duty", "Van E550 Super Duty", "Windstar", "Other"
    ],
    "GMC": [
        "Acadia", "Hummer EV", "Jimmy, Full Size", "Jimmy, S10/S15", "Safari Van", "Sprint",
        "Suburban-10 (1988 Down)", "Suburban-20 (1988 Down)", "Suburban-30 (1965-1966)",
        "Suburban-1000 (1965-1966)", "Suburban-1500 (2001 Down)", "Suburban-2500 (1967 Up)",
        "Syclone", "Terrain", "Truck-1000 Series (1966 Down)", "Truck-1500 Series (1999 Down)",
        "Truck-2500 Series (2000 Down)", "Truck-3500 Series (2001 Down)", "Truck-Canyon",
        "Truck-Envoy", "Truck-Envoy XL", "Truck-Envoy XUV", "Truck-Forward Control",
        "Truck-S10/S15/Sonoma", "Truck-Sierra 1500 (1999 Up)", "Truck-Sierra 2500 (1999 Up)",
        "Truck-Sierra 3500 (2001 Up)", "Truck-Sierra Denali", "Truck-Sierra Denali 1500 (2011 Up)",
        "Truck-Sierra Denali 2500 (2011 Up)", "Truck-Sierra Denali 3500 (2011 Up)", "Truck-Topkick",
        "Truck-Yukon (except XL)", "Truck-Yukon XL1500", "Truck-Yukon XL2500", "Typhoon",
        "Van 1000", "Van 1500", "Van 2500", "Van 3500", "Van Savana 1500", "Van Savana 2500",
        "Van Savana 3500"
    ],
    "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
    "Geo": ["Metro", "Prizm", "Spectrum", "Storm", "Tracker"],
    "Honda": ["600", "Accord", "Acty", "Civic", "Clarity", "Clarity Electric", "Clarity Fuel Cell",
              "Crosstour", "CRV", "CRX", "CRZ", "DelSol", "Element", "FCX", "Fit", "HRV",
              "Insight", "Odyssey", "Passport", "Pilot", "Prelude", "Ridgeline", "S2000"],
    "Hummer": ["H1", "H2", "H3"],
    "Hyundai": ["Accent", "Azera", "Elantra", "Entourage", "Equus", "Excel", "Genesis", "Ioniq",
                "Ioniq 5", "Ioniq 6", "Kona", "Kona Electric", "Nexo", "Palisade", "Pony", "Santa Cruz",
                "Santa Fe", "Scoupe", "Sonata", "Stellar", "Tiburon", "Tucson", "Veloster", "Venue",
                "Veracruz", "XG Series"],
    "IH": ["Pickup & Travelall", "Scout & Scout II", "Truck (Big)"],
    "Infiniti": [
        "EX35", "EX37", "FX", "G20", "G25", "G35", "G37", "I30", "I35", "J30", "JX35", "M30", "M35", "M37", 
        "M45", "M56", "Q40", "Q45", "Q50", "Q60", "Q70", "QX4", "QX30", "QX50", "QX55", "QX56", "QX60", "QX70", "QX80"
    ],
    "Isuzu": [
        "Amigo", "Ascender", "Axiom", "Gemini", "IMark", "Impulse", "Oasis", "Optima", "Reach", "Rodeo", "Stylus", 
        "Trooper/Trooper II", "Truck (Big)", "Truck-(Mini Pickup)", "Truck-(Mini Pickup) Hombre", "Truck i280 (Pickup)", 
        "Truck i290 (Pickup)", "Truck i350 (Pickup)", "Truck i370 (Pickup)", "Vehicross"
    ],
    "Jaguar": [
        "120", "140", "150", "E Pace", "F Pace", "F Type", "I Pace", "Mark 10", "S Type", "Sedan", 
        "Vanden Plas (1997 Down)", "Vanden Plas (1998 to 2007)", "Vanden Plas (2008 Up)", "X Type", 
        "XE", "XF", "XF Sportbrake", "XJ Series (2008 Up)", "XJR (1993)", "XJR (1995 to 1997)", 
        "XJR (1998 to 2007)", "XJR (2008 Up)", "XJS", "XJ6", "XJ8 (2008 Up)", "XJ8 (2007 Down)", 
        "XJ12", "XK Series (2007 Up)", "XKE", "XKR (2006 Down)", "XKR (2007 Up)", "XK8"
    ],
    "Jeep": [
        "Cherokee (except Grand Cherokee)", "CJSeries", "Comanche", "Commander", "Compass", "DJ Series", 
        "FC Series", "Gladiator", "Grand Cherokee", "Grand Wagoneer", "J-Series", "Jeepster", 
        "Liberty", "Patriot", "Renegade", "Station Wagon", "Truck", "Wagoneer (except Grand Wagoneer)", "Wrangler"
    ],
    "Kia": [
        "Amanti", "Besta", "Borrego", "Cadenza", "Carnival", "EV6", "Forte", "K5", "K900", 
        "Magentis", "Niro", "Niro EV", "Optima", "Rio", "Rondo", "Sedona", "Seltos", 
        "Sephia", "Sorento", "Soul", "Spectra", "Sportage", "Stinger", "Telluride"
    ],
    "LandRover": [
        "Defender (1997 Down)", "Defender (2020 Up)", "Discovery (2004 Down)", "Discovery (2017 Up)", 
        "Discovery Sport", "Freelander", "LR2", "LR3", "LR4", "Range Rover", 
        "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar", "Other"
    ],
    "Lexus": [
        "CT 200H", "ES250", "ES300", "ES300H", "ES330", "ES350", "GS200t", "GS300", 
        "GS350", "GS400", "GS430", "GS450", "GS460", "GS F", "GX460", "GX470", 
        "HS250H", "IS200t", "IS250", "IS300", "IS350", "IS500", "IS F", "LC500", 
        "LC500h", "LFA", "LS400", "LS430", "LS460", "LS500", "LS500h", "LS600HL", 
        "LX450", "LX470", "LX570", "LX600", "NX200t", "NX250", "NX300", "NX300h", 
        "NX350", "NX350H", "NX450h+", "RC 200t", "RC 300", "RC 350", "RC F", 
        "RX300", "RX330", "RX350", "RX350h", "RX350L", "RX400h", "RX450 Hybrid", 
        "RX450 Hybrid L", "RX500h", "RZ450e", "SC (excl 430)", "SC430", "UX 200", "UX 250h"
    ],
    "Lincoln": [
        "Aviator", "Blackwood", "Continental", "Corsair", "LS", "Mark LT", "Mark Series", 
        "MKC", "MKS", "MKT", "MKX", "MKZ", "Nautilus", "Navigator", "Versailles", 
        "Zephyr", "Other (includes Town Car)"
    ],
    "Maserati": ["BiTurbo", "Ghibli", "GranTurismo", "Grecale", "Grecale GT", "Levante", "Quattroporte"],
    "Mazda": [
        "2", "3", "5", "6", "323", "626", "808", "929", "1200", "1800", "Cosmo", "CX3", "CX5", 
        "CX7", "CX9", "CX30", "CX50", "CX90", "GLC", "MPV Van", "MX3", "MX6", "MX30", "Miata MX5", 
        "Millenia", "Navajo", "Pickup-B1600", "Pickup-B1800", "Pickup-B2000", "Pickup-B2200", 
        "Pickup-B2300", "Pickup-B2500", "Pickup-B2600", "Pickup-B3000", "Pickup-B4000", "Pickup-Rotary", 
        "Protege", "RX2", "RX3", "RX4", "RX7", "RX8", "Tribute"
    ],
    "McLaren": [
        "570GT", "570S", "600LT", "620R", "650S", "675LT", "720S", "765LT", "Artura", "GT", 
        "MP4 12C", "P1", "Senna"
    ],
    "Mercedes": [
        "170", "190", "200", "218", "219", "220", "230-4 Cyl", "230-6 Cyl", "240D", "250", "260E", 
        "280", "300D (includes CD/D/SD/TD)", "300E", "300SL", "320", "350", "380", "400", "420", "450", 
        "500", "560", "600", "AMG GT", "A Class", "B Class", "C Class", "CL Class", "CLA Class", 
        "CLK", "CLS", "E Class", "EQB Class", "EQE Class", "EQE Class SUV", "EQS Class", "EQS Class SUV", 
        "G Class", "GL Class", "GLA Class", "GLB Class", "GLC Class", "GLE Class", "GLK Class", 
        "GLS Class", "ML Series", "Metris", "R Class", "S Class", "SL Class", "SLC Class", "SLK", "SLR", 
        "SLS", "Sprinter 1500", "Sprinter 2500", "Sprinter 3500", "Sprinter 4500", "Truck"
    ],
    "Mercury": [
        "Bobcat", "Capri", "Comet", "Cougar", "Grand Marquis (1979 Down)", "Grand Marquis (1980 Up)", 
        "LN7", "Lynx (except LN7)", "Marauder", "Mariner", "Marquis (not Grand)", 
        "Merkur (includes XR4TI and Scorpio)", "Milan", "Monarch", "Montego", "Monterey", "Mountaineer", 
        "Mystique", "Sable", "Topaz", "Tracer", "Villager", "Zephyr", "Other"
    ],
    "MG": ["MGB", "Midget", "Other"],
    "Mini": [
        "(Austin)", "Cooper", "Cooper Clubman", "Cooper Countryman", "Cooper Paceman"
    ],
    "Mitsubishi": [
        "3000", "Cordia", "Diamante", "Eclipse", "Eclipse Cross", "Endeavor", "Expo", "Fuso", 
        "Galant", "i MiEV", "Lancer", "Minicab", "Mirage", "Montero", "Montero-Sport", "Outlander", 
        "Outlander Sport", "Pickup (See also Dodge D50)", "Precis", "Raider", "RVR", "Sigma", 
        "Space Wagon", "Starion", "Tredia", "Van"
    ],
    "Nissan": [
        "1200", "1600", "200SX", "210", "240SX", "240Z", "260Z", "280-Z", "280-ZX", "300ZX", "350Z", 
        "370Z", "310", "311", "410", "411", "510", "610", "710", "810", "Almera", "Altima", "Ariya", 
        "Armada", "Axxess", "B210", "Cube", "F10", "Frontier", "GTR", "Juke", "Kicks", "Leaf", 
        "Lucino", "Maxima (1981 Down)", "Maxima (1982 Up)", "Micra", "Murano", "NV 200", "NV 1500", 
        "NV 2500", "NV 3500", "NX", "Pathfinder", "Patrol", "Platina", "Pulsar", "Qashqai", "Quest", 
        "Rogue", "Rogue Sport", "Sentra", "Stanza (Excl Van)", "Stanza Van", "Tida", "Truck", 
        "Truck-Titan", "Truck-Titan XD", "Tsubame", "UD Series", "Van GC22", "Versa", "X Trail", 
        "Xterra", "Z"
    ],
    "Oldsmobile": [
        "88 (1979 Down)", "88 (1980 Up)", "98 (1979 Down)", "98 (1980 Up)", "Achieva", "Alero",
        "Aurora", "Bravada", "Calais (1984 Down)", "Calais (1985 Up)", "Ciera", "Custom Cruiser (1979 Down)",
        "Custom Cruiser (1980 Up)", "Cutlass (1972 Down)", "Cutlass (1973 Up)", "F85", "Firenza", "Intrigue",
        "Omega", "Silhouette", "Starfire", "Supreme-Calais (1988 Up)", "Supreme-Cutlass (1988 Up)",
        "Supreme (1972 Down)", "Supreme (1973-1987)", "Toronado", "Other"
    ],
    "Peugeot": [
        "304", "403", "404", "405", "504", "505", "604"
    ],
    "Plymouth": [
        "Acclaim", "Arrow-Car", "Arrow-Truck (See also Dodge D50)", "Barracuda", "Breeze", "Caravelle",
        "Champ", "Cricket", "Duster (1970-1976)", "Duster (1979-1980)", "Duster (1985-1987)", "Duster (1992-1994)",
        "Grand Fury (1979 Down)", "Grand Fury (1980 Up)", "Horizon", "Laser", "Neon", "Prowler", "Reliant",
        "Sapporo", "Scamp (1983 only)", "Scamp (except 1983)", "Sundance", "Trailduster", "Valiant",
        "Van 100", "Van 150", "Van 200", "Van 250", "Van 300", "Van 350", "Volare", "Voyager", "Other"
    ],
    "Pontiac": [
        "1000", "2000-P/J/Sunbird", "6000", "Acadian", "Astre", "Aztek", "Bonneville (1979 Down)", "Bonneville (1980 Up)",
        "Catalina (1979 Down)", "Catalina (1980 Up)", "Fiero", "Firebird", "Firefly", "G3", "G4", "G5", "G6", "G8",
        "Grand AM", "Grand Prix", "GTO (New Style)", "GTO (Old Style)", "Lemans", "Matiz", "Montana",
        "Parisienne (1979 Down)", "Parisienne (1980 Up)", "Phoenix", "Pursuit", "Solstice", "Sunbird", "Sunburst",
        "Sunfire", "Sunrunner", "Tempest", "Torrent", "Trans Sport", "Van-Montana", "Ventura", "Vibe", "Wave", "Other"
    ],
    "Porsche": [
        "356", "911/930", "912/e", "914", "918", "924", "928", "944", "968", "Boxster", "Carrera-GT",
        "Cayenne", "Cayman S", "Macan", "Panamera", "Taycan"
    ],
    "Ram": [
        "Promaster 1500", "Promaster 2500", "Promaster 3500", "Promaster City", "Truck 1500 Series",
        "Truck 2500 Series", "Truck 3500 Series", "Truck 4500 Series", "Truck 5500 Series"
    ],
    "Renault": [
        "18i", "5", "9i", "Alliance", "Clio", "Encore", "Fuego", "Gordini", "Lecar/R5", "Medallion", "Megane",
        "R8", "R10", "R12", "R15", "R16", "R17", "R18", "R25", "R5", "R9", "Sportwagon", "Other"
    ],
    "Rivian": [
        "R1T", "R1S"
    ],
    "Rover": [
        "2000-3500", "25", "3500S", "3500SD", "3500SDS", "3500S", "3500S (SD1)", "4000", "416i", "420", "45",
        "75", "Acura", "CD", "City Rover", "Defender", "Freelander", "Land Rover", "MGF", "Maestro", "Metro",
        "Montego", "SD1", "Streetwise", "Tomcat", "Other"
    ],
    "Saab": [
        "9-2X", "9-3", "9-4X", "9-5", "9-7X", "900", "9000", "92x", "96", "96 Sport", "97 Sonnett", "99", "Sonnett",
        "Other"
    ],
    "Saturn": [
        "Astra", "Aura", "EV1", "Ion", "L Series", "Outlook", "Relay", "S Series", "Sky", "SL1", "SL2", "Vue", "Other"
    ],
    "Scion": [
        "FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD", "Other"
    ],
    "Subaru": [
        "B9 Tribeca", "Baja", "BRZ", "Crosstrek", "Forester", "Impreza", "Impreza WRX", "Justy", "Legacy",
        "Loyale", "Outback", "SVX", "Tribeca", "XT", "Other"
    ],
    "Suzuki": [
        "Aerio", "Equator", "Esteem", "Forenza", "Grand Vitara", "Kizashi", "Reno", "Samurai", "Sidekick", "SJ",
        "Swift", "SX4", "Verona", "Vitara", "X-90", "XL-7", "Other"
    ],
    "Tesla": [
        "Model 3", "Model S", "Model X", "Model Y", "Roadster", "Other"
    ],
    "Toyota": [
        "4Runner", "86", "Avalon", "C-HR", "Camry", "Celica", "Corolla", "Corona", "Cressida", "Echo", "FJ Cruiser",
        "GR Supra", "Highlander", "Land Cruiser", "Matrix", "MR2", "Paseo", "Pickup", "Previa", "Prius", "RAV4",
        "Sequoia", "Sienna", "Solara", "Starlet", "Supra", "T100", "Tacoma", "Tercel", "Tundra", "Van", "Venza", "Yaris",
        "Other"
    ],
    "Triumph": [
        "GT6", "Spitfire", "Stag", "TR2", "TR3", "TR4", "TR4A", "TR5", "TR6", "TR7", "TR8", "Other"
    ],
    "Volkswagen": [
        "Amarok", "Arteon", "Beetle", "CC", "e-Golf", "Eos", "Golf", "Jetta", "Passat", "Phaeton", "Polo", "Rabbit", "Scirocco",
        "Tiguan", "Touareg", "T-Roc", "Up!", "Other"
    ],
    "Volvo": [
        "240", "740", "850", "940", "960", "C30", "C70", "S40", "S60", "S70", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40",
        "XC60", "XC70", "XC90", "Other"
    ]


}

PARTS_CONST = [
    "A Pillar",
    "A Pillar Trim",
    "A/C Bracket",
    "A/C Compressor",
    "A/C Compressor Clutch Only",
    "A/C Condenser",
    "A/C Condenser Fan",
    "A/C Control Computer",
    "A/C Evaporator",
    "A/C Evaporator Housing only",
    "A/C Heater Control (see also Radio or TV Screen)",
    "A/C Hose",
    "A/C Wiring Harness",
    "Accelerator Cable",
    "Accelerator Parts",
    "Adaptive Cruise Projector",
    "Air Bag",
    "Air Bag Clockspring",
    "Air Bag Ctrl Module",
    "Air Box/Air Cleaner",
    "Air Cond./Heater Vents",
    "Air Flow Meter",
    "Air Pump",
    "Air Ride Compressor",
    "Air Shutter",
    "Air Tube/Resonator",
    "Alternator",
    "Alternator Bracket",
    "Amplifier/Radio",
    "Antenna",
    "Anti-Lock Brake Computer",
    "Anti-Lock Brake Pump",
    "Armrest",
    "Ash Tray/Lighter",
    "Audiovisual (A/V) (see also TV Screen)",
    "Automatic Headlight Dimmer",
    "Auto. Trans. Cooler",
    "Axle Actuator (4WD)",
    "Axle Assy Fr (4WD w. Housing)",
    "Axle Assy Rear (w. Housing)",
    "Axle Beam Front (2WD, incl I Beam Susp)",
    "Axle Beam Rear (FWD)",
    "Axle Flange",
    "Axle Housing Only",
    "Axle Shaft",
    "B Pillar Trim",
    "Back Door (above rear bumper)",
    "Back Door Glass",
    "Back Door Handle, Inside",
    "Back Door Handle, Outside",
    "Back Door Hinge",
    "Back Door Moulding",
    "Back Door Shell",
    "Back Door Trim Panel",
    "Back Glass",
    "Back Glass Regulator",
    "Back Glass Shock",
    "Backing Plate, Front",
    "Backing Plate, Rear",
    "Backup Camera",
    "Backup Light",
    "Battery",
    "Battery Cable",
    "Battery Terminal",
    "Battery Tray",
    "Bed, Pickup",
    "Bed Floor (Pickup)",
    "Bed Front Panel (Pickup)",
    "Bed Liner",
    "Bed Side, Pickup",
    "Bell Housing",
    "Belt Tensioner",
    "Blind Spot Camera",
    "Blower Motor",
    "Body Wiring Harness",
    "Brake/Clutch Pedal",
    "Brake Booster",
    "Brake Proportioning Valve",
    "Brake Rotor/Drum, Front",
    "Brake Rotor/Drum, Rear",
    "Brake Shoes/Pads",
    "Brush Guard",
    "Bug Screen",
    "Bumper Assy (Front) includes cover",
    "Bumper Assy (Rear) includes cover",
    "Bumper Bracket (Misc)",
    "Bumper Cover (Front)",
    "Bumper Cover (Rear)",
    "Bumper End Cap",
    "Bumper Energy Absorber (Front)",
    "Bumper Energy Absorber (Rear)",
    "Bumper Face Bar (Front)",
    "Bumper Face Bar (Rear)",
    "Bumper Filler Panel",
    "Bumper Guard (Front)",
    "Bumper Guard (Rear)",
    "Bumper Impact Strip",
    "Bumper Reinforcement (Front)",
    "Bumper Reinforcement (Rear)",
    "Bumper Shock",
    "Bumper Step Pad",
    "C Pillar Trim",
    "Cab",
    "Cab Back Panel",
    "Cab Clip, no cowl",
    "Cab Corner",
    "Cabin Air Filter",
    "Cabin Fuse Box",
    "Caliper",
    "Camera Projector",
    "Camshaft",
    "Camshaft Housing",
    "Carburetor (see also Throttle Body)",
    "Cargo Cover/Shade",
    "Cargo Lamp",
    "Carpet",
    "Carrier (see also Differential)",
    "Carrier Case",
    "CD Player/Radio",
    "Center Cap (Wheel)",
    "Center Pillar",
    "Charging Port Door Assembly",
    "Chassis Control Computer (not Engine)",
    "Clock",
    "Clockspring (Air Bag)",
    "Clutch Cable",
    "Clutch Disc",
    "Clutch Fork",
    "Clutch Master Cylinder",
    "Coil/Air Spring",
    "Coil/Igniter",
    "Column Switch",
    "Computer Box Engine",
    "Computer Box Not Engine",
    "Condenser",
    "Condenser/Radiator mtd. Cooling Fan",
    "Connecting Rod, Engine",
    "Console, Front",
    "Console, Rear",
    "Control Arm, Front Lower",
    "Control Arm, Front Upper",
    "Control Arm, Rear Lower",
    "Control Arm, Rear Upper",
    "Convertible Top",
    "Convertible Top Boot",
    "Convertible Top Lift",
    "Convertible Top Motor",
    "Convertible Windscreen",
    "Coolant Pump",
    "Cooling Fan (Rad and Con mtd.)",
    "Core (Radiator) Support",
    "Cowl",
    "Cowl Vent Panel",
    "Crank Pulley (Harmonic Balancer)",
    "Crankshaft",
    "Cruise Control Computer",
    "Cruise Control Servo/Regulator",
    "Cruise Speed Controler",
    "Cylinder Head (Engine)",
    "D Pillar",
    "Dash/Interior/Seat Switch",
    "Dash Bezel (see also Instrument or Radio Bezel)",
    "Dash Pad",
    "Dash Panel",
    "Dash Wiring Harness",
    "Deck Lid Assembly",
    "Deck Lid/Trunk Lid Shell",
    "Diesel Particulate Filter",
    "Differential Assembly (see also Carrier)",
    "Differential Case Only",
    "Differential Flange Only",
    "Distributor",
    "Door Back (door above rear bumper)",
    "Door Front",
    "Door Handle, Inside",
    "Door Handle, Outside",
    "Door Lock Striker",
    "Door Mirror Cover",
    "Door Outer Repair Panel, Back",
    "Door Outer Repair Panel, Front",
    "Door Outer Repair Panel, Rear",
    "Door Rear (side of vehicle)",
    "Door Shell, Back",
    "Door Shell, Front",
    "Door Shell, Rear",
    "Door Window Crank Handle",
    "Drag Link",
    "Drive-By-Wire",
    "Drive Shaft, Front",
    "Drive Shaft, Rear",
    "Driving Lamp Bezel",
    "EGR Valve",
    "Electric Door Motor (not Window)",
    "Electric Window Motor",
    "Electrical Part Misc",
    "Electronic Transmission Shifter",
    "Emblem",
    "Emergency Brake",
    "Engine",
    "Engine Block",
    "Engine Computer",
    "Engine Core",
    "Engine Cover",
    "Engine Cradle",
    "Engine Cylinder Head",
    "Engine Fuse Box",
    "Engine Mounts",
    "Engine Oil Pan",
    "Engine Wiring Harness",
    "Exhaust Assembly",
    "Exhaust Cross Pipe",
    "Exhaust Fluid Pump",
    "Exhaust Fluid Tank",
    "Exhaust Heat Shield",
    "Exhaust Lead Pipe",
    "Exhaust Manifold",
    "Exhaust Muffler",
    "Exhaust Pipe",
    "Exhaust Resonator",
    "Exhaust Tail Pipe",
    "Fan Blade",
    "Fan Clutch",
    "Fender",
    "Fender Extension/Flare",
    "Fender Inner Panel",
    "Fender Moulding",
    "Fender Skirt",
    "Fender/Wheelhouse Inner Liner",
    "Flex Plate",
    "Floor Mats",
    "Floor Pan",
    "Floor Shift Assembly",
    "Flywheel",
    "Fog Lamp",
    "Fog Lamp Bezel",
    "Fog Lamp Bracket",
    "Fog Lamp Rear",
    "Fog Lamp Switch",
    "Frame",
    "Frame Front Section Only",
    "Frame Horn",
    "Frame Upper & Lower Rails",
    "Front Axle Assembly (4WD w Housing)",
    "Front Axle Beam (2WD, incl I Beam Susp)",
    "Front Axle Shaft",
    "Front Bumper Assembly (includes cover)",
    "Front Bumper Cover",
    "Front Bumper Face Bar",
    "Front Bumper Guard",
    "Front Bumper Reinforcement",
    "Front Console",
    "Front Door",
    "Front Door Glass",
    "Front Door Handle, Inside",
    "Front Door Handle, Outside",
    "Front Door Hinge",
    "Front Door Mirror",
    "Front Door Mirror Glass",
    "Front Door Moulding",
    "Front Door Regulator",
    "Front Door Shell",
    "Front Door Switch",
    "Front Door Trim Panel",
    "Front Door Vent Glass",
    "Front Door Vent Glass Regulator",
    "Front Door Window Motor",
    "Front Drive Shaft",
    "Front End Assembly (Nose)",
    "Front Seat Belt Assembly",
    "Front Valance",
    "Front Window Regulator",
    "Fuel Cap",
    "Fuel Cell",
    "Fuel Cooler",
    "Fuel Distributor (& Misc. Injection)",
    "Fuel Filler Door",
    "Fuel Filler Neck",
    "Fuel Gauge",
    "Fuel Injector (& Misc. Injection)",
    "Fuel Injector Pump",
    "Fuel Line",
    "Fuel Pump",
    "Fuel Rail (& Misc. Injection)",
    "Fuel Tank",
    "Fuel Tank Sending Unit",
    "Fuse Box (Cabin)",
    "Fuse Box (Engine)",
    "Gas Cap",
    "Gas Tank",
    "Gate Interior Trim Panel",
    "Gate Window Regulator",
    "Gate/Lid",
    "Gauge (Misc)",
    "Generator",
    "Glass, Back",
    "Glass, Front Door",
    "Glass, Front Vent",
    "Glass, Quarter Window",
    "Glass, Rear Door",
    "Glass, Rear Vent",
    "Glass, Special (see also Sunroof/TTop)",
    "Glass, Windshield",
    "Glove Box",
    "GPS Screen (see also Radio or Heater/AC Control)",
    "Grille",
    "Grille Moulding",
    "Grille Surround",
    "Harmonic Balancer (Crank Pulley)",
    "Hatch/Trunk Lid",
    "Head (Cylinder)",
    "Header Panel",
    "Headlight Assembly",
    "Headlight Ballast",
    "Headlight Bracket",
    "Headlight Bucket",
    "Headlight Bulb",
    "Headlight Cover (Plastic)",
    "Headlight Door",
    "Headlight Housing",
    "Headlight Igniter",
    "Headlight Lens",
    "Headlight Motor",
    "Headlight Switch (Column Mounted)",
    "Headlight Switch (Dash Mounted)",
    "Headlight Switch (see also Column Switch)",
    "Headlight Washer Motor Only",
    "Headlight Wiper Motor Only",
    "Headliner",
    "Headrest",
    "Heads Up Display",
    "Heater Assy",
    "Heater Core",
    "Heater Motor",
    "Heater/AC Control (see also Radio or TV Screen)",
    "Hood",
    "Hood Deflector",
    "Hood Hinge",
    "Hood Insulation Pad",
    "Hood Latch",
    "Hood Ornament",
    "Hood Prop",
    "Hood Scoop",
    "Hood Shock",
    "Horn",
    "Hub",
    "Hub Cap/Wheel Cover (display w image)",
    "Hub Cap/Wheel Cover (display w/o image)",
    "Hub, Lockout (4WD)",
    "HVAC Actuator",
    "Hybrid Converter/Inverter",
    "Idler Arm",
    "Ignition Module (see also Ignitor/Coil)",
    "Ignition Switch",
    "Ignitor/Coil",
    "Info Screen (see also Radio or Heater/AC Control)",
    "Information Label",
    "Inside Door Handle",
    "Instrument Cluster (see also Speedo)",
    "Instrument Cluster Bezel",
    "Instrument Face Plate",
    "Intake Manifold",
    "Intercooler",
    "Intercooler Pipe",
    "Interior Complete",
    "Interior Light",
    "Interior Trim Panel (Gate/Lid)",
    "Interior Trim Panel (Quarter)",
    "Interior Trim Panel, Door (Back)",
    "Interior Trim Panel, Door (Front)",
    "Interior Trim Panel, Door (Rear)",
    "Inverter Cooler",
    "Jack Assembly",
    "Keys/Latches and Locks",
    "Key Remote/Fob",
    "Kick Panel",
    "Knee Assembly (see also Strut Assy)",
    "Lamp Wiring Harness",
    "Latch, Front Door",
    "Latch, Rear Door",
    "Latch, Back Door",
    "Latches",
    "Leaf Spring, Front",
    "Leaf Spring, Rear",
    "License Lamp",
    "License Plate Bracket",
    "Lid/Gate",
    "Lid Interior Trim Panel",
    "Liftgate Assembly",
    "Liftgate Shell",
    "Lock Actuator",
    "Lockout Hub, 4X4",
    "Locks",
    "Lug Wrench",
    "Luggage Rack",
    "Marker/Fog Light, Front",
    "Marker/Side Light, Rear",
    "Master Cylinder",
    "Mirror, Door",
    "Mirror, Rear View",
    "Misc. Electrical",
    "Moulding (Back Door)",
    "Moulding (Fender)",
    "Moulding (Front Door)",
    "Moulding (Lid/Hatch/Gate)",
    "Moulding (Quarter Panel/Bed Side)",
    "Moulding (Rear Door)",
    "Moulding (Rocker)",
    "Moulding (Windshield)",
    "Mouldings (Misc)",
    "Mud Flap",
    "Neutral Safety Switch",
    "Night Vision Camera",
    "Nose (Front End Assembly)",
    "Oil Cooler",
    "Oil Filter Adapter",
    "Oil Pan, Engine",
    "Oil Pan, Transmission",
    "Oil Pump, Engine",
    "Outside Door Handle",
    "Overdrive Unit (see also Transmission)",
    "Owners Manual",
    "Paddle Shifter",
    "Park/Fog Lamp Front",
    "Parcel Shelf",
    "Park Lamp Rear (Side)",
    "Parking Assist Camera",
    "Pickup Bed",
    "Pickup Bed Floor",
    "Pickup Bed Front Panel",
    "Pickup Bed Side",
    "Pickup Cap/Camper Shell",
    "Piston",
    "Pitman Arm",
    "Power Brake Booster",
    "Power Inverter (Hybrid)",
    "Power Steering Assy",
    "Power Steering Control Valve",
    "Power Steering Cooler",
    "Power Steering Motor",
    "Power Steering Pressure Cyl",
    "Power Steering Pressure Hose",
    "Power Steering Pump",
    "Power Steering Rack/Box/Gear",
    "Power Steering Reservoir",
    "Pressure Plate",
    "Push Rod (Engine)",
    "Quarter Interior Trim Panel",
    "Quarter Moulding",
    "Quarter Panel",
    "Quarter Panel Extension",
    "Quarter Repair Panel",
    "Quarter Window",
    "Quarter Window Motor",
    "Quarter Window Regulator",
    "Rack & Pinion (Steering)",
    "Radiator",
    "Radiator/Condenser mtd. Cooling Fan",
    "Radiator Air Shutter",
    "Radiator Core Support",
    "Radiator Cover Baffle",
    "Radiator Fan Shroud",
    "Radiator Overflow Bottle",
    "Radio/CD (see also A/C Control or TV Screen)",
    "Radio Bezel Trim",
    "Radio Face Plate",
    "Radius Arm, Front",
    "Rag Joint (see also Steering Coupler)",
    "Rear Axle Assy (RWD)",
    "Rear Axle Beam (FWD)",
    "Rear Body Panel",
    "Rear Bumper Assembly (includes cover)",
    "Rear Bumper Cover",
    "Rear Bumper Face Bar",
    "Rear Bumper Guard",
    "Rear Bumper Reinforcement/Misc",
    "Rear Clip",
    "Rear Console",
    "Rear Crossmember",
    "Rear Door (side of vehicle)",
    "Rear Door Handle, Inside",
    "Rear Door Handle, Outside",
    "Rear Door Hinge",
    "Rear Door Moulding",
    "Rear Door Regulator",
    "Rear Door Shell",
    "Rear Door Switch",
    "Rear Door Trim Panel",
    "Rear Door Vent Glass",
    "Rear Door Vent Glass regulator",
    "Rear Door Window",
    "Rear Door Window Motor",
    "Rear Door Window Regulator",
    "Rear Drive Shaft",
    "Rear Finish Panel",
    "Rear Gate/Lid",
    "Rear Gate Window Motor",
    "Rear Seat Belt Assembly",
    "Rear Knuckle/Stub Axle",
    "Rear Lower Valance",
    "Rear Suspension (see also Control Arms)",
    "Rear Suspension Locating Arm",
    "Rear Suspension Trailing Arm",
    "Rear Window Defogger",
    "Rear Window Washer Motor",
    "Receiver Dryer",
    "Relay (Misc)",
    "Ring and Pinion Only",
    "Rocker Arm",
    "Rocker Moulding",
    "Rocker Panel (see also Center Pillar)",
    "Roll Bar",
    "Roll Bar Padding",
    "Roof",
    "Roof Glass Frame/Track",
    "Roof Panel (see also Sunroof)",
    "Roof Rack",
    "Running Boards",
    "Running Board Motor",
    "Seat, Back (3rd Row)",
    "Seat, Back (4th Row)",
    "Seat, Back (5th Row)",
    "Seat, Front",
    "Seat, Rear (2nd Row)",
    "Seat Belt, Front",
    "Seat Belt, Rear",
    "Seat Belt Motor",
    "Seat Belt Pretensioner",
    "Seat Belt Track (Electric)",
    "Seat Motor",
    "Seat Switch",
    "Seat Track, Front Only",
    "Sensor (Body, Misc)",
    "Sensor (Chassis, Misc)",
    "Sensor (Drivetrain, Misc)",
    "Shifter Assembly (Floor)",
    "Shifter Linkage",
    "Shock Absorber",
    "Shock Mount",
    "Sill Plate",
    "Skid Plate",
    "Slave Cylinder",
    "Smog Pump",
    "Spare Tire Carrier",
    "Spare Tire Cover",
    "Spare Tire Hoist",
    "Speaker",
    "Special Glass",
    "Speedometer (see also Instr. Cluster)",
    "Speedometer Cable",
    "Spindle",
    "Spoiler, Front",
    "Spoiler, Rear",
    "Spring Hanger",
    "Stabilizer Bar Only",
    "Starter",
    "Steering Column",
    "Steering Column Shaft",
    "Steering Coupler",
    "Steering Knuckle (see also Knee & Strut)",
    "Steering Pump",
    "Steering Rack/Box/Gear",
    "Steering Wheel",
    "Strut (see also Knee Assy)",
    "Strut Tower Brace",
    "Sun Roof / T-Top",
    "Sun Roof Motor",
    "Sunvisor",
    "Supercharger/Turbocharger",
    "Tachometer",
    "Tail Light",
    "Tail Light Circuit Board",
    "Tail Light Lens",
    "Tailgate Cable",
    "Tailgate/Trunk Lid",
    "Tailgate Hinge",
    "Tailgate Lift Motor",
    "Tailgate Shell",
    "Tailgate Window Regulator",
    "Thermostat Housing",
    "Third Brake Light",
    "Throttle Body/Throttle Valve Housing",
    "Throwout Bearing",
    "Tie Rod",
    "Timing Belt/Chain",
    "Timing Cover",
    "Timing Gears",
    "Tire",
    "Tonneau Cover",
    "Torque Convertor",
    "Torsion Bar",
    "Tow Hook",
    "Track/Watts Linkage",
    "Trailer Brake Controller",
    "Trailer Hitch",
    "Trans OD Unit (see also Transmission)",
    "Transaxle Housing Only",
    "Transfer Case",
    "Transfer Case Adapter",
    "Transfer Case Core",
    "Transfer Case Electric Motor",
    "Transfer Case Switch",
    "Transmission",
    "Transmission Bellhousing Only",
    "Transmission Clutch Actuator",
    "Transmission Computer",
    "Transmission Core",
    "Transmission Crossmember",
    "Transmission Front Pump",
    "Transmission Mount",
    "Transmission Pan",
    "Transmission Torque Converter",
    "Transmission Valve Body",
    "Transmission Wiring Harness",
    "Trim Ring",
    "Trunk Lid Pull Down Motor",
    "Trunk Lid/Hatch",
    "Trunk Lid/Hatch Hinge",
    "Trunk Lid/Hatch Shock",
    "Trunk Lid/Tailgate Moulding",
    "TTop/Sunroof",
    "Turbo/Supercharger Core",
    "Turbocharger/Supercharger",
    "Turn Signal/Fog Lamp",
    "TV Screen (see also Radio or Heater/AC Control)",
    "Uniside",
    "Vacuum Pump",
    "Vacuum Storage Tank",
    "Valance, Front",
    "Valance, Rear",
    "Valve Cover",
    "Vapor Canister",
    "Voltage Regulator",
    "Washer Nozzle",
    "Water Pump",
    "Water Separator",
    "Weather Stripping",
    "Wheel (display w image)",
    "Wheel (display w/o image)",
    "Wheel Bearing",
    "Wheel Cover/Hubcap (display w image)",
    "Wheel Cover/Hubcap (display w/o image)",
    "Wheel Lug Nut",
    "Wheel Opening Moulding",
    "Wheelchair Lift",
    "Wheelchair Ramp",
    "Wheelhouse (Rear)",
    "Winch",
    "Window Motor",
    "Window Regulator (Front)",
    "Window Regulator (Rear)",
    "Window Shade",
    "Window Switch (Front Door)",
    "Window Switch (Rear Door)",
    "Window Washer Motor, Rear",
    "Windshield",
    "Windshield Frame",
    "Windshield Hinge",
    "Windshield Washer Motor (Front)",
    "Windshield Washer Reservoir",
    "Wiper Arm",
    "Wiper Linkage",
    "Wiper Motor, Front (Windshield)",
    "Wiper Motor, Rear",
    "Wiring Harness (Air Conditioning)",
    "Wiring Harness (Body)",
    "Wiring Harness (Dash)",
    "Wiring Harness (Engine)",
    "Wiring Harness (Lamp)",
    "Wiring Harness (Misc)",
    "Wiring Harness (Transmission)",
    "Yoke/U-Joint"
]

DAMAGE_TYPE_CONST = [
    "All Over",
    "Biohazard/Chemical",
    "Burn",
    "Burn - Engine",
    "Burn - Interior",
    "Damage History",
    "Frame Damage",
    "Front End",
    "Hail",
    "Mechanical",
    "Minor Dents/Scratches",
    "Missing/Altered VIN",
    "Normal Wear",
    "Partial Repair",
    "Rear End",
    "Rejected Repair",
    "Replaced VIN",
    "Rollover",
    "Side",
    "Stripped",
    "Top/Roof",
    "Undercarriage"
    "Unknown",
    "Vandalism",
    "Water/Flood"
]

CATEGORY_CONST = [
    'INCOMING',
    'NO TITLE',
    'NEEDS A STICKER',
    'TITLE PROBLEM',
    'VIN NOT IN SYSTEM',
    'PRE DRAIN',
    'DRAINING',
    "PRE YARD",
    "YARD",
    "ENROUTE",
    "PAPERWORK",
    "PROCESSING",
    "YARD",
    "IMPOUND",
    "FOR SALE",
    "SOLD",
    "CRUSHED",
]

TRANSMISSION_CONST = [
    "Automatic",
    "Manual",
    "CVT",
    "DCT",
    "Automated-Manual",
    "Other"
]

COLORS_CONST = [
    "Beige",
    "Black",
    "Blue",
    "Brown",
    "Burgundy",
    "Charcoal",
    "Gold",
    "Grey",
    "Green",
    "Maroon",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Silver",
    "Tan",
    "Teal",
    "White",
    "Yellow",
    "Other"
]

SELLER_TYPE_CONST = [
        'COPART',
        'IAA',
        'Street',
        'Charity',
        'Vendor',
    ]

STATE_CHOICES = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
]

STATE_ABBRV = [
    'AL',
    'AK',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'FL',
    'GA',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY',
]

STATE_ABBRV_CHOICES = (
    (abbrv, abbrv) for abbrv in STATE_ABBRV
)

PARTS_CATEGORY_DICT = {
    "A Pillar": 262152,
    "A Pillar Trim": 33654, 
    "A/C Bracket": 33543,
    "A/C Compressor": 33543,
    "A/C Compressor Clutch Only": 33543,
    "A/C Condenser": 61864,
    "A/C Condenser Fan": 33547,
    "A/C Control Computer": 33545,
    "A/C Evaporator": 33547,
    "A/C Evaporator Housing only": 33547,
    "A/C Heater Control (see also Radio or TV Screen)": 33545,
    "A/C Hose": 33544,
    "A/C Wiring Harness": 33545,
    "Adaptive Cruise Projector": 38728,
    "Air Bag": 262196,
    "Air Bag Clockspring": 262196,
    "Air Bag Ctrl Module": 262196,
    "Air Box/Air Cleaner": 33549,
    "Air Cond./Heater Vents": 33545,
    "Air Flow Meter": 33557,
    "Air Pump": 33557,
    "Air Ride Compressor": 33557,
    "Air Shutter": 33557,
    "Air Tube/Resonator": 33557,
    "Alternator": 177697,
    "Alternator Bracket": 177698,
    "Amplifier/Radio": 33545,
    "Antenna": 33639,
    "Anti-Lock Brake Computer": 33559,
    "Anti-Lock Brake Pump": 33559,
    "Armrest": 33694,
    "Ash Tray/Lighter": 262198,
    "Audiovisual (A/V) (see also TV Screen)": 33545,
    "Automatic Headlight Dimmer": 33707,
    "Auto. Trans. Cooler": 33599,
    "Axle Actuator (4WD)": 262238,
    "Axle Assy Fr (4WD w. Housing)": 262238,
    "Axle Assy Rear (w. Housing)": 262238,
    "Axle Beam Front (2WD, incl I Beam Susp)": 262238,
    "Axle Beam Rear (FWD)": 262238,
    "Axle Flange": 262238,
    "Axle Housing Only": 262238,
    "Axle Shaft": 262238,
    "Battery": 179846,
    "Battery Cable": 179847,
    "Battery Terminal": 179847,
    "Battery Tray": 179847,
    "Bed, Pickup": 262175,
    "Bed Floor (Pickup)": 262175,
    "Bed Front Panel (Pickup)": 262175,
    "Bed Liner": 262175,
    "Bed Side, Pickup": 262175,
    "Bell Housing": 33612,
    "Belt Tensioner": 262060,
    "Blind Spot Camera": 262068,
    "Blower Motor": 33546,
    "Body Wiring Harness": 33545,
    "Brake/Clutch Pedal": 262198,
    "Brake Booster": 174021,
    "Brake Proportioning Valve": 33559,
    "Brake Rotor/Drum, Front": 33564,
    "Brake Rotor/Drum, Rear": 33565,
    "Brake Shoes/Pads": 57357,
    "Brush Guard": 262153,
    "Bug Screen": 262153,
    "Bumper Assy (Front) includes cover": 262145,
    "Bumper Assy (Rear) includes cover": 262145,
    "Bumper Bracket (Misc)": 262145,
    "Bumper Cover (Front)": 262145,
    "Bumper Cover (Rear)": 262145,
    "Bumper End Cap": 262145,
    "Bumper Energy Absorber (Front)": 262145,
    "Bumper Energy Absorber (Rear)": 262145,
    "Bumper Face Bar (Front)": 262145,
    "Bumper Face Bar (Rear)": 262145,
    "Bumper Filler Panel": 262145,
    "Bumper Guard (Front)": 262145,
    "Bumper Guard (Rear)": 262145,
    "Bumper Impact Strip": 262145,
    "Bumper Reinforcement (Front)": 262145,
    "Bumper Reinforcement (Rear)": 262145,
    "Bumper Shock": 262145,
    "Bumper Step Pad": 262145,
    "Cab": 33637,
    "Cab Back Panel": 33637,
    "Cab Clip, no cowl": 33637,
    "Cab Corner": 33637,
    "Cabin Air Filter": 61117,
    "Cabin Fuse Box": 262198,
    "Caliper": 33563,
    "Camera Projector": 262068,
    "Camshaft": 33612,
    "Camshaft Housing": 33612,
    "Carburetor (see also Throttle Body)": 33550,
    "Cargo Cover/Shade": 174084,
    "Cargo Lamp": 33694,
    "Carpet": 33694,
    "Carrier (see also Differential)": 262244,
    "Carrier Case": 262244,
    "CD Player/Radio": 33545,
    "Center Cap (Wheel)": 33747,
    "Charging Port Door Assembly": 262098,
    "Chassis Control Computer (not Engine)": 33545,
    "Clock": 33694,
    "Clockspring (Air Bag)": 262196,
    "Clutch Cable": 262239,
    "Clutch Disc": 262239,
    "Clutch Fork": 262239,
    "Clutch Master Cylinder": 262239,
    "Coil/Air Spring": 33582,
    "Coil/Igniter": 262183,
    "Column Switch": 262196,
    "Computer Box Engine": 33545,
    "Computer Box Not Engine": 33545,
    "Condenser": 61864,
    "Condenser/Radiator mtd. Cooling Fan": 33546,
    "Connecting Rod, Engine": 33612,
    "Console, Front": 262188,
    "Console, Rear": 262188,
    "Control Arm, Front Lower": 33581,
    "Control Arm, Front Upper": 33581,
    "Control Arm, Rear Lower": 33581,
    "Control Arm, Rear Upper": 33581,
    "Convertible Top": 262170,
    "Convertible Top Boot": 262170,
    "Convertible Top Lift": 262170,
    "Convertible Top Motor": 262170,
    "Convertible Windscreen": 262170,
    "Coolant Pump": 33604,
    "Cooling Fan (Rad and Con mtd.)": 33600,
    "Core (Radiator) Support": 33600,
    "Cowl": 33637,
    "Cowl Vent Panel": 33637,
    "Crank Pulley (Harmonic Balancer)": 33612,
    "Crankshaft": 33612,
    "Cruise Control Computer": 38728,
    "Cruise Control Servo/Regulator": 38728,
    "Cruise Speed Controler": 38728,
    "Cylinder Head (Engine)": 33612,
    "Dash/Interior/Seat Switch": 262196,
    "Dash Bezel (see also Instrument or Radio Bezel)": 33694,
    "Dash Pad": 33694,
    "Dash Panel": 33694,
    "Dash Wiring Harness": 33694,
    "Deck Lid Assembly": 33637,
    "Deck Lid/Trunk Lid Shell": 33637,
    "Diesel Particulate Filter": 33605,
    "Differential Assembly (see also Carrier)": 262244,
    "Differential Case Only": 262244,
    "Differential Flange Only": 262244,
    "Distributor": 33687,
    "Door Back (door above rear bumper)": 33637,
    "Door Front": 33637,
    "Door Handle, Inside": 33637,
    "Door Handle, Outside": 33637,
    "Door Lock Striker": 33637,
    "Door Mirror Cover": 33637,
    "Door Outer Repair Panel, Back": 33637,
    "Door Outer Repair Panel, Front": 33637,
    "Door Outer Repair Panel, Rear": 33637,
    "Door Rear (side of vehicle)": 33637,
    "Door Shell, Back": 33637,
    "Door Shell, Front": 33637,
    "Door Shell, Rear": 33637,
    "Door Window Crank Handle": 33637,
    "Drag Link": 33579,
    "Drive-By-Wire": 262198,
    "Drive Shaft, Front": 262238,
    "Drive Shaft, Rear": 262238,
    "Driving Lamp Bezel": 262212,
    "EGR Valve": 33605,
    "Electric Door Motor (not Window)": 262116,
    "Electric Window Motor": 262116,
    "Electrical Part Misc": 262116,
    "Electronic Transmission Shifter": 262259,
    "Emblem": 33643,
    "Emergency Brake": 262092,
    "Engine": 33612,
    "Engine Block": 33612,
    "Engine Computer": 33545,
    "Engine Core": 33612,
    "Engine Cover": 33612,
    "Engine Cradle": 33612,
    "Engine Cylinder Head": 33612,
    "Engine Fuse Box": 262221,
    "Engine Mounts": 50454,
    "Engine Oil Pan": 38657,
    "Engine Wiring Harness": 262116,
    "Exhaust Assembly": 33605,
    "Exhaust Cross Pipe": 33605,
    "Exhaust Fluid Pump": 33605,
    "Exhaust Fluid Tank": 33605,
    "Exhaust Heat Shield": 174044,
    "Exhaust Lead Pipe": 33605,
    "Exhaust Manifold": 33632,
    "Exhaust Muffler": 33636,
    "Exhaust Pipe": 33633,
    "Exhaust Resonator": 33636,
    "Exhaust Tail Pipe": 33633,
    "Fan Blade": 262119,
    "Fan Clutch": 262120,
    "Fender": 33637,
    "Fender Extension/Flare": 33637,
    "Fender Inner Panel": 33637,
    "Fender Moulding": 33637,
    "Fender Skirt": 33637,
    "Fender/Wheelhouse Inner Liner": 33637,
    "Flex Plate": 33732,
    "Floor Mats": 33697,
    "Floor Pan": 33637,
    "Floor Shift Assembly": 262259,
    "Flywheel": 33732,
    "Fog Lamp": 33709,
    "Fog Lamp Bezel": 33709,
    "Fog Lamp Bracket": 33709,
    "Fog Lamp Rear": 33709,
    "Fog Lamp Switch": 33709,
    "Frame": 33637,
    "Frame Front Section Only": 33637,
    "Frame Horn": 33637,
    "Frame Upper & Lower Rails": 33637,
    "Front Axle Assembly (4WD w Housing)": 262238,
    "Front Axle Beam (2WD, incl I Beam Susp)": 262238,
    "Front Axle Shaft": 262238,
    "Front Bumper Assembly (includes cover)": 262145,
    "Front Bumper Cover": 262145,
    "Front Bumper Face Bar": 262145,
    "Front Bumper Guard": 262145,
    "Front Bumper Reinforcement": 262145,
    "Front Console": 262188,
    "Front Door": 33637,
    "Front Door Glass": 33683,
    "Front Door Handle, Inside": 33637,
    "Front Door Handle, Outside": 33637,
    "Front Door Hinge": 33637,
    "Front Door Mirror": 262160,
    "Front Door Mirror Glass": 262160,
    "Front Door Moulding": 33637,
    "Front Door Regulator": 33683,
    "Front Door Shell": 33637,
    "Front Door Switch": 33683,
    "Front Door Trim Panel": 33694,
    "Front Door Vent Glass": 33683,
    "Front Door Vent Glass Regulator": 33683,
    "Front Door Window Motor": 262116,
    "Front Drive Shaft": 262238,
    "Front End Assembly (Nose)": 33637,
    "Front Seat Belt Assembly": 33725,
    "Front Valance": 33637,
    "Front Window Regulator": 33683,
    "Fuel Cap": 262072,
    "Fuel Cell": 262094,
    "Fuel Cooler": 33612,
    "Fuel Distributor (& Misc. Injection)": 262070,
    "Fuel Filler Door": 262072,
    "Fuel Filler Neck": 262072,
    "Fuel Gauge": 33672,
    "Fuel Injector (& Misc. Injection)": 33554,
    "Fuel Injector Pump": 33554,
    "Fuel Line": 173950,
    "Fuel Pump": 33555,
    "Fuel Rail (& Misc. Injection)": 33554,
    "Fuel Tank": 33556,
    "Fuel Tank Sending Unit": 33555,
    "Fuse Box (Cabin)": 262221,
    "Fuse Box (Engine)": 262221,
    "Gas Cap": 262072,
    "Gas Tank": 33556,
    "Gate Interior Trim Panel": 33694,
    "Gate Window Regulator": 33683,
    "Gate/Lid": 33637,
    "Gauge (Misc)": 33672,
    "Generator": 177697,
    "Glass, Back": 33683,
    "Glass, Front Door": 33683,
    "Glass, Front Vent": 33683,
    "Glass, Quarter Window": 33683,
    "Glass, Rear Door": 33683,
    "Glass, Rear Vent": 33683,
    "Glass, Special (see also Sunroof/TTop)": 33683,
    "Glass, Windshield": 33683,
    "Glove Box": 33694,
    "GPS Screen (see also Radio or Heater/AC Control)": 33672,
    "Grille": 33645,
    "Grille Moulding": 33645,
    "Grille Surround": 33645,
    "Harmonic Balancer (Crank Pulley)": 33612,
    "Hatch/Trunk Lid": 33637,
    "Head (Cylinder)": 33612,
    "Header Panel": 33637,
    "Headlight Assembly": 33710,
    "Headlight Ballast": 33710,
    "Headlight Bracket": 33710,
    "Headlight Bucket": 33710,
    "Headlight Bulb": 33710,
    "Headlight Cover (Plastic)": 33710,
    "Headlight Door": 33710,
    "Headlight Housing": 33710,
    "Headlight Igniter": 33710,
    "Headlight Lens": 33710,
    "Headlight Motor": 33710,
    "Headlight Switch (Column Mounted)": 33710,
    "Headlight Switch (Dash Mounted)": 33710,
    "Headlight Switch (see also Column Switch)": 33710,
    "Headlight Washer Motor Only": 33710,
    "Headlight Wiper Motor Only": 33710,
    "Headliner": 174080,
    "Headrest": 33701,
    "Heads Up Display": 33712,
    "Heater Assy": 33542,
    "Heater Core": 262081,
    "Heater Motor": 33546,
    "Heater/AC Control (see also Radio or TV Screen)": 33545,
    "Hood": 33637,
    "Hood Deflector": 33637,
    "Hood Hinge": 33637,
    "Hood Insulation Pad": 33637,
    "Hood Latch": 33637,
    "Hood Ornament": 33637,
    "Hood Prop": 33637,
    "Hood Scoop": 33637,
    "Hood Shock": 33637,
    "Horn": 262159,
    "Hub": 33743,
    "Hub Cap/Wheel Cover (display w image)": 33747,
    "Hub Cap/Wheel Cover (display w/o image)": 33747,
    "Hub, Lockout (4WD)": 262238,
    "HVAC Actuator": 262083,
    "Hybrid Converter/Inverter": 262259,
    "Idler Arm": 33581,
    "Ignition Module (see also Ignitor/Coil)": 262183,
    "Ignition Switch": 262184,
    "Ignitor/Coil": 262183,
    "Info Screen (see also Radio or Heater/AC Control)": 33672,
    "Information Label": 33637,
    "Inside Door Handle": 33637,
    "Instrument Cluster (see also Speedo)": 33672,
    "Instrument Cluster Bezel": 33672,
    "Instrument Face Plate": 33672,
    "Intake Manifold": 36474,
    "Intercooler": 262073,
    "Intercooler Pipe": 262073,
    "Interior Complete": 33694,
    "Interior Light": 33712,
    "Interior Trim Panel (Gate/Lid)": 33694,
    "Interior Trim Panel (Quarter)": 33694,
    "Interior Trim Panel, Door (Back)": 33694,
    "Interior Trim Panel, Door (Front)": 33694,
    "Interior Trim Panel, Door (Rear)": 33694,
    "Inverter Cooler": 262259,
    "Jack Assembly": 262265,
    "Keys/Latches and Locks": 33648,
    "Key Remote/Fob": 33648,
    "Kick Panel": 33694,
    "Knee Assembly (see also Strut Assy)": 33579,
    "Lamp Wiring Harness": 33707,
    "Latch, Front Door": 33637,
    "Latch, Rear Door": 33637,
    "Latch, Back Door": 33637,
    "Latches": 33648,
    "Leaf Spring, Front": 33582,
    "Leaf Spring, Rear": 33582,
    "License Lamp": 33712,
        "License Plate Bracket": 33637,
    "Lid/Gate": 33637,
    "Lid Interior Trim Panel": 33694,
    "Liftgate Assembly": 262175,
    "Liftgate Shell": 262175,
    "Lock Actuator": 33648,
    "Lockout Hub, 4X4": 262238,
    "Locks": 33648,
    "Lug Wrench": 33749,
    "Luggage Rack": 33651,
    "Marker/Fog Light, Front": 33709,
    "Marker/Side Light, Rear": 33717,
    "Master Cylinder": 33566,
    "Mirror, Door": 262160,
    "Mirror, Rear View": 33699,
    "Misc. Electrical": 262116,
    "Moulding (Back Door)": 33637,
    "Moulding (Fender)": 33637,
    "Moulding (Front Door)": 33637,
    "Moulding (Lid/Hatch/Gate)": 33637,
    "Moulding (Quarter Panel/Bed Side)": 33637,
    "Moulding (Rear Door)": 33637,
    "Moulding (Rocker)": 33637,
    "Moulding (Windshield)": 33637,
    "Mouldings (Misc)": 33637,
    "Mud Flap": 33637,
    "Neutral Safety Switch": 262259,
    "Night Vision Camera": 262068,
    "Nose (Front End Assembly)": 33637,
    "Oil Cooler": 33612,
    "Oil Filter Adapter": 33612,
    "Oil Pan, Engine": 38657,
    "Oil Pan, Transmission": 33612,
    "Oil Pump, Engine": 6778,
    "Outside Door Handle": 33637,
    "Overdrive Unit (see also Transmission)": 262259,
    "Owners Manual": 33637,
    "Paddle Shifter": 262259,
    "Park/Fog Lamp Front": 33709,
    "Parcel Shelf": 33694,
    "Park Lamp Rear (Side)": 33717,
    "Parking Assist Camera": 258037,
    "Pickup Bed": 262175,
    "Pickup Bed Floor": 262175,
    "Pickup Bed Front Panel": 262175,
    "Pickup Bed Side": 262175,
    "Pickup Cap/Camper Shell": 262175,
    "Piston": 33623,
    "Pitman Arm": 33587,
    "Power Brake Booster": 174021,
    "Power Inverter (Hybrid)": 262259,
    "Power Steering Assy": 33588,
    "Power Steering Control Valve": 33588,
    "Power Steering Cooler": 33588,
    "Power Steering Motor": 33588,
    "Power Steering Pressure Cyl": 33588,
    "Power Steering Pressure Hose": 262225,
    "Power Steering Pump": 33588,
    "Power Steering Rack/Box/Gear": 33589,
    "Power Steering Reservoir": 33588,
    "Pressure Plate": 262239,
    "Push Rod (Engine)": 33624,
    "Quarter Interior Trim Panel": 33694,
    "Quarter Moulding": 33637,
    "Quarter Panel": 33637,
    "Quarter Panel Extension": 33637,
    "Quarter Repair Panel": 33637,
    "Quarter Window": 33683,
    "Quarter Window Motor": 262116,
    "Quarter Window Regulator": 33683,
    "Rack & Pinion (Steering)": 33589,
    "Radiator": 33602,
    "Radiator/Condenser mtd. Cooling Fan": 33546,
    "Radiator Air Shutter": 33602,
    "Radiator Core Support": 33600,
    "Radiator Cover Baffle": 33602,
    "Radiator Fan Shroud": 33602,
    "Radiator Overflow Bottle": 33602,
    "Radio/CD (see also A/C Control or TV Screen)": 33545,
    "Radio Bezel Trim": 33545,
    "Radio Face Plate": 33545,
    "Radius Arm, Front": 33587,
    "Rag Joint (see also Steering Coupler)": 33589,
    "Rear Axle Assy (RWD)": 262238,
    "Rear Axle Beam (FWD)": 262238,
    "Rear Body Panel": 33637,
    "Rear Bumper Assembly (includes cover)": 262145,
    "Rear Bumper Cover": 262145,
    "Rear Bumper Face Bar": 262145,
    "Rear Bumper Guard": 262145,
    "Rear Bumper Reinforcement/Misc": 262145,
    "Rear Clip": 33637,
    "Rear Console": 262188,
    "Rear Crossmember": 33637,
    "Rear Door (side of vehicle)": 33637,
    "Rear Door Handle, Inside": 33637,
    "Rear Door Handle, Outside": 33637,
    "Rear Door Hinge": 33637,
    "Rear Door Moulding": 33637,
    "Rear Door Regulator": 33683,
    "Rear Door Shell": 33637,
    "Rear Door Switch": 33683,
    "Rear Door Trim Panel": 33694,
    "Rear Door Vent Glass": 33683,
    "Rear Door Vent Glass regulator": 33683,
    "Rear Door Window": 33683,
    "Rear Door Window Motor": 262116,
    "Rear Door Window Regulator": 33683,
    "Rear Drive Shaft": 262238,
    "Rear Finish Panel": 33637,
    "Rear Gate/Lid": 33637,
    "Rear Gate Window Motor": 262116,
    "Rear Seat Belt Assembly": 33725,
    "Rear Knuckle/Stub Axle": 262230,
    "Rear Lower Valance": 33637,
    "Rear Suspension (see also Control Arms)": 33579,
    "Rear Suspension Locating Arm": 33579,
    "Rear Suspension Trailing Arm": 33579,
    "Rear Window Defogger": 33699,
    "Rear Window Washer Motor": 33699,
    "Receiver Dryer": 262076,
    "Relay (Misc)": 262221,
    "Ring and Pinion Only": 262244,
    "Rocker Arm": 33624,
    "Rocker Moulding": 33637,
    "Rocker Panel (see also Center Pillar)": 33637,
    "Roll Bar": 33637,
    "Roll Bar Padding": 33637,
    "Roof": 33637,
    "Roof Glass Frame/Track": 33637,
    "Roof Panel (see also Sunroof)": 33637,
    "Roof Rack": 33651,
    "Running Boards": 33650,
    "Running Board Motor": 33650,
    "Seat, Back (3rd Row)": 33701,
    "Seat, Back (4th Row)": 33701,
    "Seat, Back (5th Row)": 33701,
    "Seat, Front": 33701,
    "Seat, Rear (2nd Row)": 33701,
    "Seat Belt, Front": 33725,
    "Seat Belt, Rear": 33725,
    "Seat Belt Motor": 33725,
    "Seat Belt Pretensioner": 33725,
    "Seat Belt Track (Electric)": 33725,
    "Seat Motor": 33701,
    "Seat Switch": 33701,
    "Seat Track, Front Only": 33701,
    "Sensor (Body, Misc)": 33545,
    "Sensor (Chassis, Misc)": 33545,
    "Sensor (Drivetrain, Misc)": 33545,
    "Shifter Assembly (Floor)": 262259,
    "Shifter Linkage": 262259,
    "Shock Absorber": 33590,
    "Shock Mount": 33590,
    "Sill Plate": 33637,
    "Skid Plate": 33637,
    "Slave Cylinder": 262239,
    "Smog Pump": 33605,
    "Spare Tire Carrier": 262174,
    "Spare Tire Cover": 262174,
    "Spare Tire Hoist": 262174,
    "Speaker": 33545,
    "Special Glass": 33683,
    "Speedometer (see also Instr. Cluster)": 33672,
    "Speedometer Cable": 33672,
    "Spindle": 33589,
    "Spoiler, Front": 33638,
    "Spoiler, Rear": 33638,
    "Spring Hanger": 33579,
    "Stabilizer Bar Only": 33592,
    "Starter": 177699,
    "Steering Column": 174093,
    "Steering Column Shaft": 174093,
    "Steering Coupler": 174093,
    "Steering Knuckle (see also Knee & Strut)": 262230,
    "Steering Pump": 33588,
    "Steering Rack/Box/Gear": 33589,
    "Steering Wheel": 33704,
    "Strut (see also Knee Assy)": 33590,
    "Strut Tower Brace": 33590,
    "Sun Roof / T-Top": 262,
        "Sun Roof / T-Top": 262172,
    "Sun Roof Motor": 262172,
    "Sunvisor": 46102,
    "Supercharger/Turbocharger": 33741,
    "Tachometer": 33672,
    "Tail Light": 33716,
    "Tail Light Circuit Board": 33716,
    "Tail Light Lens": 33716,
    "Tailgate Cable": 262178,
    "Tailgate/Trunk Lid": 33637,
    "Tailgate Hinge": 262178,
    "Tailgate Lift Motor": 262178,
    "Tailgate Shell": 262178,
    "Tailgate Window Regulator": 33683,
    "Thermostat Housing": 33603,
    "Third Brake Light": 33707,
    "Throttle Body/Throttle Valve Housing": 33558,
    "Throwout Bearing": 262239,
    "Tie Rod": 33593,
    "Timing Belt/Chain": 262134,
    "Timing Cover": 262136,
    "Timing Gears": 262137,
    "Tire": 179680,
    "Tonneau Cover": 33655,
    "Torque Convertor": 63692,
    "Torsion Bar": 33582,
    "Tow Hook": 262233,
    "Track/Watts Linkage": 33579,
    "Trailer Brake Controller": 33570,
    "Trailer Hitch": 33653,
    "Trans OD Unit (see also Transmission)": 262259,
    "Transaxle Housing Only": 262259,
    "Transfer Case": 262256,
    "Transfer Case Adapter": 262256,
    "Transfer Case Core": 262256,
    "Transfer Case Electric Motor": 262256,
    "Transfer Case Switch": 262256,
    "Transmission": 171115,
    "Transmission Bellhousing Only": 262259,
    "Transmission Clutch Actuator": 262259,
    "Transmission Computer": 33596,
    "Transmission Core": 262259,
    "Transmission Crossmember": 262259,
    "Transmission Front Pump": 262259,
    "Transmission Mount": 262258,
    "Transmission Pan": 262259,
    "Transmission Torque Converter": 63692,
    "Transmission Valve Body": 262259,
    "Transmission Wiring Harness": 262259,
    "Trim Ring": 33747,
    "Trunk Lid Pull Down Motor": 33637,
    "Trunk Lid/Hatch": 33637,
    "Trunk Lid/Hatch Hinge": 33637,
    "Trunk Lid/Hatch Shock": 33637,
    "Trunk Lid/Tailgate Moulding": 33637,
    "TTop/Sunroof": 262172,
    "Turbo/Supercharger Core": 33741,
    "Turbocharger/Supercharger": 33741,
    "Turn Signal/Fog Lamp": 33717,
    "TV Screen (see also Radio or Heater/AC Control)": 33545,
    "Uniside": 33637,
    "Vacuum Pump": 33626,
    "Vacuum Storage Tank": 33626,
    "Valance, Front": 33637,
    "Valance, Rear": 33637,
    "Valve Cover": 33621,
    "Vapor Canister": 261899,
    "Voltage Regulator": 33577,
    "Washer Nozzle": 174113,
    "Water Pump": 33604,
    "Water Separator": 33612,
    "Weather Stripping": 33637,
    "Wheel (display w image)": 179679,
    "Wheel (display w/o image)": 179679,
    "Wheel Bearing": 170141,
    "Wheel Cover/Hubcap (display w image)": 33747,
    "Wheel Cover/Hubcap (display w/o image)": 33747,
    "Wheel Lug Nut": 33749,
    "Wheel Opening Moulding": 33637,
    "Wheelchair Lift": 262197,
    "Wheelchair Ramp": 262197,
    "Wheelhouse (Rear)": 33637,
    "Winch": 33637,
    "Window Motor": 262116,
    "Window Regulator (Front)": 33683,
    "Window Regulator (Rear)": 33683,
    "Window Shade": 262204,
    "Window Switch (Front Door)": 262116,
    "Window Switch (Rear Door)": 262116,
    "Window Washer Motor, Rear": 262179,
    "Windshield": 33683,
    "Windshield Frame": 33683,
    "Windshield Hinge": 33683,
    "Windshield Washer Motor (Front)": 262179,
    "Windshield Washer Reservoir": 262179,
    "Wiper Arm": 61941,
    "Wiper Linkage": 61941,
    "Wiper Motor, Front (Windshield)": 61941,
    "Wiper Motor, Rear": 61941,
    "Wiring Harness (Air Conditioning)": 262116,
    "Wiring Harness (Body)": 262116,
    "Wiring Harness (Dash)": 262116,
    "Wiring Harness (Engine)": 262116,
    "Wiring Harness (Lamp)": 262116,
    "Wiring Harness (Misc)": 262116,
    "Wiring Harness (Transmission)": 262116,
    "Yoke/U-Joint": 262252,
}


   

