# Generated by Django 3.2.23 on 2024-06-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0008_auto_20240629_1529'),
        ('company', '0002_auto_20240619_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ebay_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay.ebaycredential'),
        ),
        migrations.AddField(
            model_name='company',
            name='ebay_merchant_location_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
