# Generated by Django 3.2.23 on 2024-01-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20240128_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='main_contact',
        ),
    ]
