# Generated by Django 3.2.23 on 2024-01-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Location Name'),
        ),
    ]
