# Generated by Django 4.2.6 on 2024-05-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_location_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_core_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
