# Generated by Django 3.2.23 on 2024-06-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20240619_2233'),
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('Payment', 'Payment'), ('Shipping', 'Shipping'), ('Return', 'Return')], max_length=100)),
                ('policy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
