# Generated by Django 3.2.23 on 2024-06-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20240619_2233'),
        ('ebay', '0005_auto_20240626_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EbayCredentials',
            new_name='EbayCredential',
        ),
    ]
