# Generated by Django 3.2.23 on 2024-06-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0006_rename_ebaycredentials_ebaycredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycredential',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ebaycredential',
            name='token',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
