# Generated by Django 3.2.23 on 2024-06-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0007_auto_20240627_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(blank=True, max_length=100, null=True)),
                ('tree_id', models.IntegerField(blank=True, null=True)),
                ('tree_version', models.IntegerField(blank=True, null=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ebaycredential',
            old_name='company',
            new_name='company_ref',
        ),
        migrations.AddField(
            model_name='ebaycredential',
            name='fulfillment_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_policy', to='ebay.ebaypolicy'),
        ),
        migrations.AddField(
            model_name='ebaycredential',
            name='payment_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_policy', to='ebay.ebaypolicy'),
        ),
        migrations.AddField(
            model_name='ebaycredential',
            name='return_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_policy', to='ebay.ebaypolicy'),
        ),
        migrations.AddField(
            model_name='ebaypolicy',
            name='policy_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
