# Generated by Django 3.2.23 on 2024-07-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0009_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaycredential',
            name='company_ref',
        ),
    ]
