# Generated by Django 3.2.23 on 2024-06-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partebaycategoryspecification',
            old_name='ebay_category',
            new_name='ebay_category_id',
        ),
    ]
