# Generated by Django 3.2.23 on 2024-01-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20240121_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ebay_application_token',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='user',
            name='ebay_user_refresh_token',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='user',
            name='ebay_user_token',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
