# Generated by Django 4.2.6 on 2024-02-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_is_main_comany_contact_user_is_main_company_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_pull_it_account',
            field=models.BooleanField(default=False),
        ),
    ]
