# Generated by Django 4.2.6 on 2024-02-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_location_latitude_location_longitude'),
        ('Authentication', '0007_user_u_pull_it_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.location'),
        ),
    ]
