# Generated by Django 4.2.6 on 2024-03-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='funnelSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('yard_size', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
